# version: '3.8'

services:
  jwt-simple-auth:
    build:
      context: ./backend/node/micro-services/auth-services/jwt-simple-auth
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    network_host: "host"

  simple-auth:
    container_name: be-simple-auth
    build:
      context: ./backend/node/micro-services/auth-services/simple-auth
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    network_mode: "host" 

  simple-todo:
    container_name: ui-simple-todo
    build:
      context: ./front-end/angular-projects/simple-todo
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0 --port 4200
    environment:
      - NODE_ENV=production
    network_mode: "host" 

networks:
  app-network:
    driver: bridge
